name: host-docker-push
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "tag: git tag"
        required: false

jobs:
  push-docker:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./host
          file: ./host/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simple-dotnet-diagnostics:latest